language: ruby
rvm:
  - 1.8.7

script:
  #- "ln -s manifests/moco-config.pp manifests/config.pp"
  #- "ln -s manifests/moco-nodes.pp manifests/nodes.pp"
  - "puppet parser validate `find modules -name '*.pp'`"
  - "puppet-lint --no-arrow_alignment-check --no-80chars-check \
      --no-documentation-check --no-double_quoted_strings-check \
      --no-variable_scope-check --no-case_without_default-check \
      --no-variables_not_enclosed-check --no-only_variable_string-check \
      --no-ensure_first_param-check --no-unquoted_file_mode-check \
      --no-variable_contains_dash-check --no-parameter_order-check \
      --no-file_mode-check --no-nested_classes_or_defines \
      --no-quoted_booleans --no-puppet_url_without_modules \
      --no-selector_inside_resource --no-unquoted_resource_title \
      --no-names_containing_dash \
      --log-format '%{path} - %{KIND}: %{message} on line %{line} - %{check}'
      modules"

gemfile: .gemfile

# currently cannot customise per user fork, see:
# https://github.com/travis-ci/travis-ci/issues/1094
# please comment out this section in your personal fork!
notifications:
  irc:
    channels:
      - "irc.mozilla.org#callek"
    on_success: always
    on_failure: always
    template:
      - "\x02%{repository}\x0314#%{build_number}\x03\x02 (%{branch} - %{commit} : %{author}): \x02\x0312%{message}\x02\x03"
      - "\x02Change view\x02 : \x0314%{compare_url}\x03"
      - "\x02Build details\x02 : \x0314%{build_url}\x03"
      - "\x02Commit message\x02 : \x0314%{commit_message}\x03"
